#############################################################
#
# Copyright 2015 F4E | European Joint Undertaking for ITER 
#  and the Development of Fusion Energy ('Fusion for Energy')
# 
# Licensed under the EUPL, Version 1.1 or - as soon they 
# will be approved by the European Commission - subsequent  
# versions of the EUPL (the "Licence"); 
# You may not use this work except in compliance with the 
# Licence. 
# You may obtain a copy of the Licence at: 
#  
# http://ec.europa.eu/idabc/eupl
#
# Unless required by applicable law or agreed to in 
# writing, software distributed under the Licence is 
# distributed on an "AS IS" basis, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
# express or implied. 
# See the Licence for the specific language governing 
# permissions and limitations under the Licence. 
#
# $Id: Makefile.inc 3 2012-01-15 16:26:07Z aneto $
#
#############################################################

TARGET=cov

include Makefile.inc

LIBRARIES_STATIC=CRCGAM/cov/CRCGAMTest$(LIBEXT)
LIBRARIES_STATIC+=IOGAM/cov/IOGAMTest$(LIBEXT)
LIBRARIES_STATIC+=ConstantGAM/cov/ConstantGAMTest$(LIBEXT)
LIBRARIES_STATIC+=ConversionGAM/cov/ConversionGAMTest$(LIBEXT)
LIBRARIES_STATIC+=DoubleHandshakeGAM/cov/DoubleHandshakeGAMTest$(LIBEXT)
LIBRARIES_STATIC+=FilterGAM/cov/FilterGAMTest$(LIBEXT)
LIBRARIES_STATIC+=HistogramGAM/cov/HistogramGAMTest$(LIBEXT)
LIBRARIES_STATIC+=Interleaved2FlatGAM/cov/Interleaved2FlatGAMTest$(LIBEXT)
LIBRARIES_STATIC+=MathExpressionGAM/cov/MathExpressionGAMTest$(LIBEXT)
LIBRARIES_STATIC+=MessageGAM/cov/MessageGAMTest$(LIBEXT)
LIBRARIES_STATIC+=MuxGAM/cov/MuxGAMTest$(LIBEXT)
LIBRARIES_STATIC+=PIDGAM/cov/PIDGAMTest$(LIBEXT)
LIBRARIES_STATIC+=SSMGAM/cov/SSMGAMTest$(LIBEXT)
LIBRARIES_STATIC+=StatisticsGAM/cov/StatisticsGAMTest$(LIBEXT)
LIBRARIES_STATIC+=TimeCorrectionGAM/cov/TimeCorrectionGAMTest$(LIBEXT)
LIBRARIES_STATIC+=WaveformGAM/cov/WaveformGAMTest$(LIBEXT)

ifdef EFDA_MARTe_DIR
LIBRARIES_STATIC+=BaseLib2GAM/cov/BaseLib2GAMTest$(LIBEXT)
endif

ifdef MATLAB_DIR
LIBRARIES_STATIC+=SimulinkWrapperGAM/cov/SimulinkWrapperGAMTest$(LIBEXT)
endif

