/**
 * @file NI9157TestsAndFwSettings.h
 * @brief Header file for class NI9157TestsAndFwSettings.
 * @date 23/03/2021
 * @author Pedro Lourenco
 *
 * @copyright Copyright 2015 F4E | European Joint Undertaking for ITER and
 * the Development of Fusion Energy ('Fusion for Energy').
 * Licensed under the EUPL, Version 1.1 or - as soon they will be approved
 * by the European Commission - subsequent versions of the EUPL (the "Licence")
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at: http://ec.europa.eu/idabc/eupl
 *
 * @warning Unless required by applicable law or agreed to in writing, 
 * software distributed under the Licence is distributed on an "AS IS"
 * basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the Licence permissions and limitations under the Licence.
 *
 * @details This header file contains the declaration of the paths and settings
 * used in the test firmwares of the NI9157 MARTe2-components DataSource,
 * with all of its public, protected and private members. It may also include
 * definitions for inline methods which need to be visible to the compiler.
 */

#ifndef NI9157TESTSANDFWSETTINGS_H_
#define NI9157TESTSANDFWSETTINGS_H_

/*---------------------------------------------------------------------------*/
/*                        Standard header includes                           */
/*---------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------*/
/*                        Project header includes                            */
/*---------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------*/
/*                           Class declaration                               */
/*---------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------*/
/*                        Inline method definitions                          */
/*---------------------------------------------------------------------------*/

/**
 * The number of devices to be test. Must match firmware config paths.
 */
const MARTe::uint32 nDevices                = 2;

/**
 * Test for all devices (true) or until one matches the firmware config paths
 * (false).
 */
const bool testAllRetTrue                   = false;

/**
 * Number of required parameters per bitstream (ID, FILE, SIGNATURE)
 */
const MARTe::uint32 nParams                 = 3;

/**
 * Path to the forder containing the LabView bitstream files.
 */
const MARTe::char8 * const firmwarePath     = "Test/Components/Interfaces/NI9157Device/TestLvFw";

/**
 * General Purpose Firmware with U64 W/R FIFOs multiple type registers, compiled for NI9157 and NI9159.
 */
const MARTe::char8 * const multiIOFirmware[]   = {"RIO0", "NiFpga_NI9157_MultiIO.lvbitx", "F14C2F2560ABDC0BF142DDAEF1716110",
                                                "RIO1", "NiFpga_NI9159_MultiIO.lvbitx", "03AB279CA6C34216C3ABAADB90262282"};

/**
 * Firmware with BOOL W/R FIFOs, compiled for NI9157 and NI9159.
 */
const MARTe::char8 * const boolFirmware[]   = {"RIO0", "NiFpga_NI9157_BoolFifoLoop.lvbitx", "3F31F91CF1327BF3DD74027A50C336AD",
                                                "RIO1", "NiFpga_NI9159_BoolFifoLoop.lvbitx", "4142897BDB5954CCE158C05C634F4D61"};

/**
 * Firmware with U8 W/R FIFOs, compiled for NI9157 and NI9159.
 */
const MARTe::char8 * const u8Firmware[]     = {"RIO0", "NiFpga_NI9157_U8FifoLoop.lvbitx", "502481EC6C37AEF24346BB8F95834660",
                                                "RIO1", "NiFpga_NI9159_U8FifoLoop.lvbitx", "E20FC0B821C53C12CDB1CF1CFFDE9E3F"};

/**
 * Firmware with I8 W/R FIFOs, compiled for NI9157 and NI9159.
 */
const MARTe::char8 * const i8Firmware[]     = {"RIO0", "NiFpga_NI9157_I8FifoLoop.lvbitx", "A0473A2546DC8CBF468B5FFCB9CE9AEA",
                                                "RIO1", "NiFpga_NI9159_I8FifoLoop.lvbitx", "1D78B0D488445F8046D8AA7841CA7F92"};

/**
 * Firmware with U16 W/R FIFOs, compiled for NI9157 and NI9159.
 */
const MARTe::char8 * const u16Firmware[]    = {"RIO0", "NiFpga_NI9157_U16FifoLoop.lvbitx", "AA4F4EA580F600CF09332D65C1B52E43",
                                                "RIO1", "NiFpga_NI9159_U16FifoLoop.lvbitx", "0682A8270DCB30912E3855297CA35C1A"};

/**
 * Firmware with I16 W/R FIFOs, compiled for NI9157 and NI9159.
 */
const MARTe::char8 * const i16Firmware[]    = {"RIO0", "NiFpga_NI9157_I16FifoLoop.lvbitx", "378C7F29D8675EE7E2002C55A95674E3",
                                                "RIO1", "NiFpga_NI9159_I16FifoLoop.lvbitx", "B2D0A5188F4DF27E5816FB536FECA87E"};

/**
 * Firmware with U32 W/R FIFOs, compiled for NI9157 and NI9159.
 */
const MARTe::char8 * const u32Firmware[]    = {"RIO0", "NiFpga_NI9157_U32FifoLoop.lvbitx", "01507C2AD9112BBD9FA982D3AAB6322C",
                                                "RIO1", "NiFpga_NI9159_U32FifoLoop.lvbitx", "E3BDC175B00D4F16FB994A1852CC695F"};

/**
 * Firmware with I32 W/R FIFOs, compiled for NI9157 and NI9159.
 */
const MARTe::char8 * const i32Firmware[]    = {"RIO0", "NiFpga_NI9157_I32FifoLoop.lvbitx", "62B58E0715D8A602D7334953AF5D7417",
                                                "RIO1", "NiFpga_NI9159_I32FifoLoop.lvbitx", "3743493619F557D68357D4D088217E05"};

/**
 * Firmware with U64 W/R FIFOs, compiled for NI9157 and NI9159.
 */
const MARTe::char8 * const u64Firmware[]    = {"RIO0", "NiFpga_NI9157_U64FifoLoop.lvbitx", "2909691577F1F92DCB4EB278D5773B31",
                                                "RIO1", "NiFpga_NI9159_U64FifoLoop.lvbitx", "D19D1491A3C597E9F3C0E56F06AA272C"};

/**
 * Firmware with I64 W/R FIFOs, compiled for NI9157 and NI9159.
 */
const MARTe::char8 * const i64Firmware[]    = {"RIO0", "NiFpga_NI9157_I64FifoLoop.lvbitx", "544FB3933331C70D8D4AE6B5C4A2ABFD",
                                                "RIO1", "NiFpga_NI9159_I64FifoLoop.lvbitx", "217E99FD109188EF37C2FCAED84AC82E"};

/**
 * Example configuration 0 to be used with the 'multiIOFirmware' LabView bitstream.
 * For NI9157MxiDataSourceGTest.
 */
const MARTe::char8 * const multiIOConfig0   = ""
    "+NiDevice = {"
    "    Class = NI9157Device"
    "    NiRioDeviceName = XptoDevice"
    "    NiRioGenFile = XptoPath"
    "    NiRioGenSignature = XptoSignature"
    "    Open = 1"
    "    Configuration = {"
    "        ControlBool_stop = 0"
    "        ControlBool_use_dsfifo_data = 0"
    "        ControlBool_use_counter = 1"
    "        ControlU32_cycle_ticks = 200"
    "        ControlU64_packet_size = 1"
    "    }"
    "}"
    "$Application1 = {"
    "    Class = RealTimeApplication"
    "    +Functions = {"
    "        Class = ReferenceContainer"
    "        +GAMA = {"
    "            Class = NI9157MxiDataSourceTestGAM1"
    "            InputSignals = {"
    "                FIFO1_U64_R = {"
    "                    DataSource = Drv1"
    "                    Type = uint64"
    "                    Frequency = 0"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 10000"
    "                }"
    "                ticks_counter = {"
    "                    DataSource = Drv1"
    "                    Type = uint32"
    "                }"
    "            }"
    "            OutputSignals = {"
    "                FIFO0_U64_W = {"
    "                    DataSource = Drv1"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 10000"
    "                }"
    "                sample_value = {"
    "                    DataSource = Drv1"
    "                    Type = uint16"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +Data = {"
    "        Class = ReferenceContainer"
    "        +Drv1 = {"
    "            Class = NI9157MxiDataSourceTestDS"
    "            NI9157DevicePath = NiDevice"
    "            RunNi = 1"
    "        }"
    "        +Timings = {"
    "            Class = TimingDataSource"
    "        }"
    "    }"
    "    +States = {"
    "        Class = ReferenceContainer"
    "        +State1 = {"
    "            Class = RealTimeState"
    "            +Threads = {"
    "                Class = ReferenceContainer"
    "                +Thread1 = {"
    "                    Class = RealTimeThread"
    "                    Functions = {GAMA}"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +Scheduler = {"
    "        Class = GAMScheduler"
    "        TimingDataSource = Timings"
    "    }"
    "}";

/**
 * Example configuration 1 to be used with the 'multiIOFirmware' LabView bitstream.
 * For NI9157MxiDataSourceGTest.
 */
const MARTe::char8 * const multiIOConfig1   = ""
    "+NiDevice = {"
    "    Class = NI9157Device"
    "    NiRioDeviceName = XptoDevice"
    "    NiRioGenFile = XptoPath"
    "    NiRioGenSignature = XptoSignature"
    "    Open = 1"
    "    Configuration = {"
    "        ControlBool_stop = 0"
    "        ControlBool_use_dsfifo_data = 0"
    "        ControlBool_use_counter = 1"
    "        ControlU32_cycle_ticks = 200"
    "        ControlU64_packet_size = 1"
    "    }"
    "}"
    "$Application1 = {"
    "    Class = RealTimeApplication"
    "    +Functions = {"
    "        Class = ReferenceContainer"
    "        +GAMA = {"
    "            Class = NI9157MxiDataSourceTestGAM1"
    "            InputSignals = {"
    "                FIFO1_U64_R = {"
    "                    DataSource = Drv1"
    "                    Type = uint64"
    "                    Frequency = 0"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 10000"
    "                }"
    "                ticks_counter = {"
    "                    DataSource = Drv1"
    "                    Type = uint32"
    "                }"
    "            }"
    "            OutputSignals = {"
    "                FIFO0_U64_W = {"
    "                    DataSource = Drv1"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 10000"
    "                }"
    "                sample_value = {"
    "                    DataSource = Drv1"
    "                    Type = uint16"
    "                }"
    "            }"
    "        }"
    "        +GAMB = {"
    "            Class = NI9157MxiDataSourceTestGAM2"
    "            InputSignals = {"
    "               FIFO1_U64_R = {"
    "                   DataSource = Drv1"
    "                   Type = uint64"
    "                   Samples = 1"
    "                   NumberOfDimensions = 1"
    "                   NumberOfElements = 10000"
    "                   PacketMemberSizes = {8, 8, 8, 8, 8}"
    "               }"
    "            }"
    "            OutputSignals = {"
    "                Signal0_U64_PacketCounter = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal1_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal2_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal3_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal4_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +Data = {"
    "        Class = ReferenceContainer"
    "        +DDB = {"
    "            Class = GAMDataSource"
    "        }"
    "        +Drv1 = {"
    "            Class = NI9157MxiDataSourceTestDS"
    "            NI9157DevicePath = NiDevice"
    "            RunNi = 1"
    "        }"
    "        +Timings = {"
    "            Class = TimingDataSource"
    "        }"
    "    }"
    "    +States = {"
    "        Class = ReferenceContainer"
    "        +State1 = {"
    "            Class = RealTimeState"
    "            +Threads = {"
    "                Class = ReferenceContainer"
    "                +Thread1 = {"
    "                    Class = RealTimeThread"
    "                    Functions = {GAMA GAMB}"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +Scheduler = {"
    "        Class = GAMScheduler"
    "        TimingDataSource = Timings"
    "    }"
    "}";

/**
 * Example configuration 2 to be used with the 'multiIOFirmware' LabView bitstream.
 * For NI9157MxiDataSourceGTest.
 */
const MARTe::char8 * const multiIOConfig2   = ""
    "+NiDevice = {"
    "    Class = NI9157Device"
    "    NiRioDeviceName = XptoDevice"
    "    NiRioGenFile = XptoPath"
    "    NiRioGenSignature = XptoSignature"
    "    Open = 1"
    "    Configuration = {"
    "        ControlBool_stop = 0"
    "        ControlBool_use_dsfifo_data = 0"
    "        ControlBool_use_counter = 1"
    "        ControlU32_cycle_ticks = 200"
    "        ControlU64_packet_size = 1"
    "    }"
    "}"
    "$Application1 = {"
    "    Class = RealTimeApplication"
    "    +Functions = {"
    "        Class = ReferenceContainer"
    "        +GAMA = {"
    "            Class = NI9157MxiDataSourceTestGAM2"
    "            InputSignals = {"
    "               FIFO1_U64_R = {"
    "                   DataSource = Drv1"
    "                   Type = uint64"
    "                   Samples = 1"
    "                   Frequency = 1"
    "                   NumberOfDimensions = 1"
    "                   NumberOfElements = 10000"
    "                   PacketMemberSizes = {8, 8, 8, 8, 4, 2, 2}"
    "               }"
    "            }"
    "            OutputSignals = {"
    "                Signal0_U64_PacketCounter = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal1_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal2_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal3_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal4_U32 = {"
    "                    Type = uint32"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal5_U16 = {"
    "                    Type = uint16"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal6_U16 = {"
    "                    Type = uint16"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "            }"
    "        }"
    "        +GAMB = {"
    "            Class = IOGAM"
    "            InputSignals = {"
    "                Signal6_U16 = {"
    "                    DataSource = DDB"
    "                    Type = uint16"
    "                    Ranges = {{0, 0}}"
    "                }"
    "            }"
    "            OutputSignals = {"
    "                sample_value = {"
    "                    DataSource = Drv1"
    "                    Type = uint16"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +Data = {"
    "        Class = ReferenceContainer"
    "        +DDB = {"
    "            Class = GAMDataSource"
    "        }"
    "        +Drv1 = {"
    "            Class = NI9157MxiDataSourceTestDS"
    "            RunNi = 1"
    "            NI9157DevicePath = NiDevice"
    "            Signals = {"
    "                sample_value = {"
    "                    Type = uint16"
    "                }"
    "            }"
    "        }"
    "        +Timings = {"
    "            Class = TimingDataSource"
    "        }"
    "    }"
    "    +States = {"
    "        Class = ReferenceContainer"
    "        +State1 = {"
    "            Class = RealTimeState"
    "            +Threads = {"
    "                Class = ReferenceContainer"
    "                +Thread1 = {"
    "                    Class = RealTimeThread"
    "                    Functions = {GAMA GAMB}"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +Scheduler = {"
    "        Class = GAMScheduler"
    "        TimingDataSource = Timings"
    "    }"
    "}";

/**
 * Example configuration 3 to be used with the 'multiIOFirmware' LabView bitstream.
 * For NI9157MxiDataSourceGTest.
 */
const MARTe::char8 * const multiIOConfig3   = ""
    "+NiDevice = {"
    "    Class = NI9157Device"
    "    NiRioDeviceName = XptoDevice"
    "    NiRioGenFile = XptoPath"
    "    NiRioGenSignature = XptoSignature"
    "    Open = 1"
    "    Configuration = {"
    "        ControlBool_stop = 0"
    "        ControlBool_use_dsfifo_data = 0"
    "        ControlBool_use_counter = 1"
    "        ControlU32_cycle_ticks = 200"
    "        ControlU64_packet_size = 1"
    "    }"
    "}"
    "$Application1 = {"
    "    Class = RealTimeApplication"
    "    +Functions = {"
    "        Class = ReferenceContainer"
    "        +GAMA = {"
    "            Class = NI9157MxiDataSourceTestGAM2"
    "            InputSignals = {"
    "               FIFO1_U64_R = {"
    "                   DataSource = Drv1"
    "                   Type = uint64"
    "                   Samples = 1"
    "                   Frequency = 1"
    "                   NumberOfDimensions = 1"
    "                   NumberOfElements = 10000"
    "                   PacketMemberSizes = {8, 8, 8, 8, 4, 2, 2}"
    "               }"
    "            }"
    "            OutputSignals = {"
    "                Signal0_U64_PacketCounter = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal1_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal2_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal3_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal4_U32 = {"
    "                    Type = uint32"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal5_U16 = {"
    "                    Type = uint16"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal6_U16 = {"
    "                    Type = uint16"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "            }"
    "        }"
    "        +GAMB = {"
    "            Class = IOGAM"
    "            InputSignals = {"
    "                Signal0_U64_PacketCounter = {"
    "                    DataSource = DDB"
    "                    Type = uint64"
    "                    Ranges = {{0, 999}}"
    "                }"
    "            }"
    "            OutputSignals = {"
    "                FIFO0_U64_W = {"
    "                    DataSource = Drv1"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 1000"
    "                    Type = uint64"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +Data = {"
    "        Class = ReferenceContainer"
    "        +DDB = {"
    "            Class = GAMDataSource"
    "        }"
    "        +Drv1 = {"
    "            Class = NI9157MxiDataSourceTestDS"
    "            RunNi = 1"
    "            NI9157DevicePath = NiDevice"
    "            Signals = {"
    "                FIFO0_U64_W = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 1000"
    "                }"
    "            }"
    "        }"
    "        +Timings = {"
    "            Class = TimingDataSource"
    "        }"
    "    }"
    "    +States = {"
    "        Class = ReferenceContainer"
    "        +State1 = {"
    "            Class = RealTimeState"
    "            +Threads = {"
    "                Class = ReferenceContainer"
    "                +Thread1 = {"
    "                    Class = RealTimeThread"
    "                    Functions = {GAMA GAMB}"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +Scheduler = {"
    "        Class = GAMScheduler"
    "        TimingDataSource = Timings"
    "    }"
    "}";

/**
 * Example configuration 4 to be used with the 'multiIOFirmware' LabView bitstream.
 * For NI9157MxiDataSourceGTest.
 */
const MARTe::char8 * const multiIOConfig4   = ""
    "+NiDevice = {"
    "    Class = NI9157Device"
    "    NiRioDeviceName = XptoDevice"
    "    NiRioGenFile = XptoPath"
    "    NiRioGenSignature = XptoSignature"
    "    Open = 1"
    "    Configuration = {"
    "        ControlBool_stop = 0"
    "        ControlBool_use_dsfifo_data = 0"
    "        ControlBool_use_counter = 1"
    "        ControlU32_cycle_ticks = 200"
    "        ControlU64_packet_size = 1"
    "    }"
    "}"
    "$Application1 = {"
    "    Class = RealTimeApplication"
    "    +Functions = {"
    "        Class = ReferenceContainer"
    "        +GAMA = {"
    "            Class = NI9157MxiDataSourceTestGAM2"
    "            InputSignals = {"
    "               FIFO1_U64_R = {"
    "                   DataSource = Drv1"
    "                   Type = uint64"
    "                   Samples = 1"
    "                   Frequency = 1"
    "                   NumberOfDimensions = 1"
    "                   NumberOfElements = 10000"
    "                   PacketMemberSizes = {8, 8, 8, 8, 4, 2, 2}"
    "               }"
    "            }"
    "            OutputSignals = {"
    "                Signal0_U64_PacketCounter = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal1_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal2_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal3_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal4_U32 = {"
    "                    Type = uint32"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal5_U16 = {"
    "                    Type = uint16"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal6_U16 = {"
    "                    Type = uint16"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "            }"
    "        }"
    "        +GAMB = {"
    "            Class = IOGAM"
    "            InputSignals = {"
    "                Signal0_U64_PacketCounter = {"
    "                    DataSource = DDB"
    "                    Type = uint64"
    "                    Ranges = {{0, 1999}}"
    "                }"
    "            }"
    "            OutputSignals = {"
    "                FIFO0_U64_W = {"
    "                    DataSource = Drv1"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    Type = uint64"
    "                }"
    "            }"
    "        }"
    "        +GAMC = {"
    "            Class = IOGAM"
    "            InputSignals = {"
    "                Signal6_U16 = {"
    "                    DataSource = DDB"
    "                    Type = uint16"
    "                    Ranges = {{1000, 1000}}"
    "                }"
    "            }"
    "            OutputSignals = {"
    "                sample_value = {"
    "                    DataSource = Drv1"
    "                    Type = uint16"
    "                }"
    "            }"
    "        }"
    "        +GAMD = {"
    "            Class = IOGAM"
    "            InputSignals = {"
    "                IndU32 = {"
    "                    DataSource = Drv1"
    "                    Type = uint32"
    "                }"
    "            }"
    "            OutputSignals = {"
    "                ContU32 = {"
    "                    DataSource = Drv1"
    "                    Type = uint32"
    "                }"
    "            }"
    "        }"
    "        +GAME = {"
    "            Class = IOGAM"
    "            InputSignals = {"
    "                ControlBool_IndBool = {"
    "                    DataSource = Drv1"
    "                    Type = uint8"
    "                }"
    "            }"
    "            OutputSignals = {"
    "                ControlBool_ContBool = {"
    "                    DataSource = Drv1"
    "                    Type = uint8"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +Data = {"
    "        Class = ReferenceContainer"
    "        +DDB = {"
    "            Class = GAMDataSource"
    "        }"
    "        +Drv1 = {"
    "            Class = NI9157MxiDataSourceTestDS"
    "            RunNi = 1"
    "            NI9157DevicePath = NiDevice"
    "            Signals = {"
    "                FIFO1_U64_R = {"
    "                    Type = uint64"
    "                }"
    "                ticks_counter = {"
    "                    Type = uint32"
    "                }"
    "                FIFO0_U64_W = {"
    "                    Type = uint64"
    "                }"
    "                sample_value = {"
    "                    Type = uint16"
    "                }"
    "                IndU32 = {"
    "                    Type = uint32"
    "                }"
    "                ContU32 = {"
    "                    Type = uint32"
    "                }"
    "                ControlBool_IndBool = {"
    "                    Type = uint8"
    "                }"
    "                ControlBool_ContBool = {"
    "                    Type = uint8"
    "                }"
    "            }"
    "        }"
    "        +Timings = {"
    "            Class = TimingDataSource"
    "        }"
    "    }"
    "    +States = {"
    "        Class = ReferenceContainer"
    "        +State1 = {"
    "            Class = RealTimeState"
    "            +Threads = {"
    "                Class = ReferenceContainer"
    "                +Thread1 = {"
    "                    Class = RealTimeThread"
    "                    Functions = {GAMA GAMB GAMC GAMD GAME}"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +Scheduler = {"
    "        Class = GAMScheduler"
    "        TimingDataSource = Timings"
    "    }"
    "}";

/**
 * Example configuration 5 to be used with the 'multiIOFirmware' LabView bitstream.
 * For NI9157CircularFifoReaderGTest.
 */
const MARTe::char8 * const multiIOConfig5   = ""
    "+NiDevice = {"
    "    Class = NI9157Device"
    "    NiRioDeviceName = XptoDevice"
    "    NiRioGenFile = XptoPath"
    "    NiRioGenSignature = XptoSignature"
    "    Open = 1"
    "    Configuration = {"
    "        ControlBool_stop = 0"
    "        ControlBool_use_dsfifo_data = 0"
    "        ControlBool_use_counter = 1"
    "        ControlU32_cycle_ticks = 200"
    "        ControlU64_packet_size = 1"
    "    }"
    "}"
    "$Application1 = {"
    "    Class = RealTimeApplication"
    "    +Functions = {"
    "        Class = ReferenceContainer"
    "        +GAMA = {"
    "            Class = NI9157CircularFifoReaderTestGAM1"
    "            InputSignals = {"
    "               Signal1 = {"
    "                   DataSource = Drv1"
    "                   Type = uint64"
    "                   Samples = 1"
    "                   Frequency = 0"
    "               }"
    "            }"
    "        }"
    "    }"
    "    +Data = {"
    "        Class = ReferenceContainer"
    "        +Drv1 = {"
    "            Class = NI9157CircularFifoReaderTestDS"
    "            NI9157DevicePath = NiDevice"
    "            NumberOfBuffers = 80"
    "            NumberOfPacketsInFIFO = 20"
    "            CheckFrame = 1"
    "            RunNi = 1"
    "            CpuMask = 8"
    "            FifoName = \"FIFO1_U64_R\""
    "            +Checker = {"
    "                Class = NI9157::CounterChecker"
    "                NumOfFrameForSync = 3"
    "                CounterStep = 2000"
    "                CheckCounterAfterNSteps = 2000"
    "                AcquireFromCounter = 2001"
    "                SampleSize = 8"
    "            }"
    "        }"
    "        +Timings = {"
    "            Class = TimingDataSource"
    "        }"
    "    }"
    "    +States = {"
    "        Class = ReferenceContainer"
    "        +State1 = {"
    "            Class = RealTimeState"
    "            +Threads = {"
    "                Class = ReferenceContainer"
    "                +Thread1 = {"
    "                    Class = RealTimeThread"
    "                    Functions = {GAMA}"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +Scheduler = {"
    "        Class = GAMScheduler"
    "        TimingDataSource = Timings"
    "    }"
    "}";

/**
 * Example configuration 6 to be used with the 'multiIOFirmware' LabView bitstream.
 * For NI9157CircularFifoReaderGTest.
 */
const MARTe::char8 * const multiIOConfig6   = ""
    "+NiDevice = {"
    "    Class = NI9157Device"
    "    NiRioDeviceName = XptoDevice"
    "    NiRioGenFile = XptoPath"
    "    NiRioGenSignature = XptoSignature"
    "    Open = 1"
    "    Configuration = {"
    "        ControlBool_stop = 0"
    "        ControlBool_use_dsfifo_data = 0"
    "        ControlBool_use_counter = 1"
    "        ControlU32_cycle_ticks = 200"
    "        ControlU64_packet_size = 1"
    "    }"
    "}"
    "$Application1 = {"
    "    Class = RealTimeApplication"
    "    +Functions = {"
    "        Class = ReferenceContainer"
    "        +GAMA = {"
    "            Class = NI9157CircularFifoReaderTestGAM2"
    "            InputSignals = {"
    "               FIFO1_U64_R = {"
    "                   DataSource = Drv1"
    "                   Type = uint64"
    "                   Samples = 1"
    "                   NumberOfDimensions = 1"
    "                   NumberOfElements = 10000"
    "                   Frequency = 1000"
    "                   PacketMemberSizes = {8, 8, 8, 8, 8}"
    "               }"
    "            }"
    "            OutputSignals = {"
    "                Signal0_U64_PacketCounter = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal1_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal2_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal3_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal4_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +Data = {"
    "        Class = ReferenceContainer"
    "        +DDB = {"
    "            Class = GAMDataSource"
    "        }"
    "        +Drv1 = {"
    "            Class = NI9157CircularFifoReaderTestDS"
    "            NI9157DevicePath = NiDevice"
    "            NumberOfBuffers = 80"
    "            NumberOfPacketsInFIFO = 20"
    "            CheckFrame = 1"
    "            RunNi = 1"
    "            CpuMask = 8"
    "            FifoName = \"FIFO1_U64_R\""
    "            +Checker = {"
    "                Class = NI9157::CounterChecker"
    "                NumOfFrameForSync = 2"
    "                CounterStep = 2000"
    "                CheckCounterAfterNSteps = 2000"
    "                AcquireFromCounter = 1"
    "                FirstPacketCounter = 1"
    "                SampleSize = 8"
    "            }"
    "        }"
    "        +Timings = {"
    "            Class = TimingDataSource"
    "        }"
    "    }"
    "    +States = {"
    "        Class = ReferenceContainer"
    "        +State1 = {"
    "            Class = RealTimeState"
    "            +Threads = {"
    "                Class = ReferenceContainer"
    "                +Thread1 = {"
    "                    Class = RealTimeThread"
    "                    Functions = {GAMA}"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +Scheduler = {"
    "        Class = GAMScheduler"
    "        TimingDataSource = Timings"
    "    }"
    "}";

/**
 * Example configuration 7 to be used with the 'multiIOFirmware' LabView bitstream.
 * For NI9157CircularFifoReaderGTest.
 */
const MARTe::char8 * const multiIOConfig7   = ""
    "+NiDevice = {"
    "    Class = NI9157Device"
    "    NiRioDeviceName = XptoDevice"
    "    NiRioGenFile = XptoPath"
    "    NiRioGenSignature = XptoSignature"
    "    Open = 1"
    "    Configuration = {"
    "        ControlBool_stop = 0"
    "        ControlBool_use_dsfifo_data = 0"
    "        ControlBool_use_counter = 1"
    "        ControlU32_cycle_ticks = 200"
    "        ControlU64_packet_size = 1"
    "    }"
    "}"
    "$Application1 = {"
    "    Class = RealTimeApplication"
    "    +Functions = {"
    "        Class = ReferenceContainer"
    "        +GAMA = {"
    "            Class = NI9157CircularFifoReaderTestGAM2"
    "            InputSignals = {"
    "               FIFO1_U64_R = {"
    "                   DataSource = Drv1"
    "                   Type = uint64"
    "                   Samples = 1"
    "                   NumberOfDimensions = 1"
    "                   NumberOfElements = 10000"
    "                   Frequency = 1000"
    "                   PacketMemberSizes = {8, 8, 8, 8, 8}"
    "               }"
    "               InternalTimeStamp = {"
    "                   DataSource = Drv1"
    "                   Type = uint64"
    "                   Samples = 1"
    "               }"
    "               ErrorCheck = {"
    "                   DataSource = Drv1"
    "                   Type = uint32"
    "                   Samples = 3"
    "               }"
    "            }"
    "            OutputSignals = {"
    "                Signal0_U64_PacketCounter = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal1_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal2_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal3_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal4_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                InternalTimeStampDDB = {"
    "                   DataSource = DDB"
    "                   Type = uint64"
    "                }"
    "                ErrorCheckDDB = {"
    "                   DataSource = DDB"
    "                   Type = uint32"
    "                   NumberOfDimensions = 1"
    "                   NumberOfElements = 3"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +Data = {"
    "        Class = ReferenceContainer"
    "        +DDB = {"
    "            Class = GAMDataSource"
    "        }"
    "        +Drv1 = {"
    "            Class = NI9157CircularFifoReaderTestDS"
    "            NI9157DevicePath = NiDevice"
    "            NumberOfBuffers = 80"
    "            NumberOfPacketsInFIFO = 20"
    "            CheckFrame = 1"
    "            RunNi = 1"
    "            CpuMask = 8"
    "            FifoName = \"FIFO1_U64_R\""
    "            +Checker = {"
    "                Class = NI9157::CounterChecker"
    "                NumOfFrameForSync = 2"
    "                CounterStep = 2000"
    "                CheckCounterAfterNSteps = 2000"
    "                AcquireFromCounter = 1"
    "                FirstPacketCounter = 1"
    "                SampleSize = 8"
    "            }"
    "        }"
    "        +Timings = {"
    "            Class = TimingDataSource"
    "        }"
    "    }"
    "    +States = {"
    "        Class = ReferenceContainer"
    "        +State1 = {"
    "            Class = RealTimeState"
    "            +Threads = {"
    "                Class = ReferenceContainer"
    "                +Thread1 = {"
    "                    Class = RealTimeThread"
    "                    Functions = {GAMA}"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +Scheduler = {"
    "        Class = GAMScheduler"
    "        TimingDataSource = Timings"
    "    }"
    "}";

/**
 * Example configuration 8 to be used with the 'multiIOFirmware' LabView bitstream.
 * For NI9157CircularFifoReaderGTest.
 */
const MARTe::char8 * const multiIOConfig8   = ""
    "+NiDevice = {"
    "    Class = NI9157Device"
    "    NiRioDeviceName = XptoDevice"
    "    NiRioGenFile = XptoPath"
    "    NiRioGenSignature = XptoSignature"
    "    Open = 1"
    "    Configuration = {"
    "        ControlBool_stop = 0"
    "        ControlBool_use_dsfifo_data = 0"
    "        ControlBool_use_counter = 1"
    "        ControlU32_cycle_ticks = 200"
    "        ControlU64_packet_size = 1"
    "    }"
    "}"
    "$Application1 = {"
    "    Class = RealTimeApplication"
    "    +Functions = {"
    "        Class = ReferenceContainer"
    "        +GAMA = {"
    "            Class = NI9157CircularFifoReaderTestGAM1"
    "            InputSignals = {"
    "               Signal1 = {"
    "                   DataSource = Drv1"
    "                   Type = uint64"
    "                   Samples = 1"
    "                   Frequency = 0"
    "               }"
    "            }"
    "        }"
    "        +GAMB = {"
    "            Class = IOGAM"
    "            InputSignals = {"
    "                Counter = {"
    "                    DataSource = Timer"
    "                    Type = uint32"
    "                }"
    "                Time = {"
    "                    Frequency = 1"
    "                    DataSource = Timer"
    "                    Type = uint32"
    "                }"
    "            }"
    "            OutputSignals = {"
    "                Counter = {"
    "                    DataSource = LoggerDataSource"
    "                    Type = uint32"
    "                }"
    "                Time = {"
    "                    DataSource = LoggerDataSource"
    "                    Type = uint32"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +Data = {"
    "        Class = ReferenceContainer"
    "        +Drv1 = {"
    "            Class = NI9157CircularFifoReaderTestDS"
    "            NI9157DevicePath = NiDevice"
    "            NumberOfBuffers = 80"
    "            NumberOfPacketsInFIFO = 20"
    "            CheckFrame = 1"
    "            RunNi = 1"
    "            CpuMask = 8"
    "            FifoName = \"FIFO1_U64_R\""
    "            +Checker = {"
    "                Class = NI9157::CounterChecker"
    "                NumOfFrameForSync = 3"
    "                CounterStep = 2000"
    "                CheckCounterAfterNSteps = 2000"
    "                AcquireFromCounter = 2001"
    "                SampleSize = 8"
    "            }"
    "        }"
    "        +LoggerDataSource = {"
    "            Class = LoggerDataSource"
    "        }"
    "        +Timings = {"
    "            Class = TimingDataSource"
    "        }"
    "        +Timer = {"
    "            Class = LinuxTimer"
    "            SleepNature = \"Default\""
    "            Signals = {"
    "                Counter = {"
    "                    Type = uint32"
    "                }"
    "                Time = {"
    "                    Type = uint32"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +States = {"
    "        Class = ReferenceContainer"
    "        +State1 = {"
    "            Class = RealTimeState"
    "            +Threads = {"
    "                Class = ReferenceContainer"
    "                +Thread1 = {"
    "                    Class = RealTimeThread"
    "                    Functions = {GAMA}"
    "                }"
    "            }"
    "        }"
    "        +State2 = {"
    "            Class = RealTimeState"
    "            +Threads = {"
    "                Class = ReferenceContainer"
    "                +Thread1 = {"
    "                    Class = RealTimeThread"
    "                    Functions = {GAMB}"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +Scheduler = {"
    "        Class = GAMScheduler"
    "        TimingDataSource = Timings"
    "    }"
    "}";

/**
 * Example configuration 9 to be used with the 'multiIOFirmware' LabView bitstream.
 * For NI9157CircularFifoReaderGTest.
 */
const MARTe::char8 * const multiIOConfig9   = ""
    "+NiDevice = {"
    "    Class = NI9157Device"
    "    NiRioDeviceName = XptoDevice"
    "    NiRioGenFile = XptoPath"
    "    NiRioGenSignature = XptoSignature"
    "    Open = 1"
    "    Configuration = {"
    "        ControlBool_stop = 0"
    "        ControlBool_use_dsfifo_data = 0"
    "        ControlBool_use_counter = 1"
    "        ControlU32_cycle_ticks = 200"
    "        ControlU64_packet_size = 1"
    "    }"
    "}"
    "$Application1 = {"
    "    Class = RealTimeApplication"
    "    +Functions = {"
    "        Class = ReferenceContainer"
    "        +GAMA = {"
    "            Class = NI9157CircularFifoReaderTestGAM2"
    "            InputSignals = {"
    "                ErrorCheck = {"
    "                    DataSource = Drv1"
    "                    Type = uint32"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 1"
    "                }"
    "                FIFO1_U64_R = {"
    "                    DataSource = Drv1"
    "                    Type = uint64"
    "                    Samples = 1"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 10000"
    "                    Frequency = 1000"
    "                    PacketMemberSizes = {8, 8, 8, 8, 8}"
    "                }"
    "            }"
    "            OutputSignals = {"
    "                SomeError = {"
    "                    Type = uint32"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 1"
    "                    DataSource = DDB"
    "                }"
    "                Signal0_U64_PacketCounter = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal1_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal2_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal3_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "                Signal4_U64 = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2000"
    "                    DataSource = DDB"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +Data = {"
    "        Class = ReferenceContainer"
    "        +DDB = {"
    "            Class = GAMDataSource"
    "        }"
    "        +Drv1 = {"
    "            Class = NI9157CircularFifoReaderTestDS"
    "            NI9157DevicePath = NiDevice"
    "            NumberOfBuffers = 80"
    "            NumberOfPacketsInFIFO = 20"
    "            CheckFrame = 1"
    "            RunNi = 1"
    "            CpuMask = 8"
    "            FifoName = \"FIFO1_U64_R\""
    "            +Checker = {"
    "                Class = NI9157::CounterChecker"
    "                NumOfFrameForSync = 2"
    "                CounterStep = 1"
    "                CheckCounterAfterNSteps = 1"
    "                AcquireFromCounter = 1"
    "                FirstPacketCounter = 1"
    "                SampleSize = 8"
    "            }"
    "        }"
    "        +Timings = {"
    "            Class = TimingDataSource"
    "        }"
    "    }"
    "    +States = {"
    "        Class = ReferenceContainer"
    "        +State1 = {"
    "            Class = RealTimeState"
    "            +Threads = {"
    "                Class = ReferenceContainer"
    "                +Thread1 = {"
    "                    Class = RealTimeThread"
    "                    Functions = {GAMA}"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +Scheduler = {"
    "        Class = GAMScheduler"
    "        TimingDataSource = Timings"
    "    }"
    "}";

/**
 * Example configuration 10 to be used with the 'multiIOFirmware' LabView bitstream.
 * For NI9157CircularFifoReaderGTest.
 */
const MARTe::char8 * const multiIOConfig10   = ""
    "+NiDevice = {"
    "    Class = NI9157Device"
    "    NiRioDeviceName = XptoDevice"
    "    NiRioGenFile = XptoPath"
    "    NiRioGenSignature = XptoSignature"
    "    Open = 1"
    "    Configuration = {"
    "        ControlBool_stop = 0"
    "        ControlBool_use_dsfifo_data = 0"
    "        ControlBool_use_counter = 1"
    "        ControlU32_cycle_ticks = 200"
    "        ControlU64_packet_size = 1"
    "    }"
    "}"
    "$Application1 = {"
    "    Class = RealTimeApplication"
    "    +Functions = {"
    "        Class = ReferenceContainer"
    "        +GAMA = {"
    "            Class = NI9157CircularFifoReaderTestGAM1"
    "            InputSignals = {"
    "                ErrorCheck = {"
    "                    DataSource = Drv1"
    "                    Type = uint32"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 1"
    "                }"
    "                FIFO1_U64_R = {"
    "                    DataSource = Drv1"
    "                    Type = uint64"
    "                    Frequency = 0"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2"
    "                }"
    "            }"
    "            OutputSignals = {"
    "                SomeError = {"
    "                    Type = uint32"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 1"
    "                    DataSource = DDB"
    "                }"
    "                Signal0_U64_PacketCounter = {"
    "                    DataSource = DDB"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +Data = {"
    "        Class = ReferenceContainer"
    "        +DDB = {"
    "            Class = GAMDataSource"
    "        }"
    "        +Drv1 = {"
    "            Class = NI9157CircularFifoReaderTestDS"
    "            NI9157DevicePath = NiDevice"
    "            NumberOfBuffers = 80"
    "            NumberOfPacketsInFIFO = 20"
    "            CheckFrame = 0"
    "            RunNi = 1"
    "            CpuMask = 8"
    "            FifoName = \"FIFO1_U64_R\""
    "            +Checker = {"
    "                Class = NI9157::CounterChecker"
    "                NumOfFrameForSync = 2"
    "                CounterStep = 1"
    "                CheckCounterAfterNSteps = 1"
    "                AcquireFromCounter = 1"
    "                FirstPacketCounter = 1"
    "                SampleSize = 8"
    "            }"
    "            Signals = {"
    "                InternalTimeStamp = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 1"
    "                }"
    "                ErrorCheck = {"
    "                    Type = uint32"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 1"
    "                }"
    "                FIFO1_U64_R = {"
    "                    Type = uint64"
    "                    NumberOfDimensions = 1"
    "                    NumberOfElements = 2"
    "                    HeaderSize = 8"
    "                }"
    "            }"
    "        }"
    "        +Timings = {"
    "            Class = TimingDataSource"
    "        }"
    "    }"
    "    +States = {"
    "        Class = ReferenceContainer"
    "        +State1 = {"
    "            Class = RealTimeState"
    "            +Threads = {"
    "                Class = ReferenceContainer"
    "                +Thread1 = {"
    "                    Class = RealTimeThread"
    "                    Functions = {GAMA}"
    "                }"
    "            }"
    "        }"
    "    }"
    "    +Scheduler = {"
    "        Class = GAMScheduler"
    "        TimingDataSource = Timings"
    "    }"
    "}";

#endif /* NI9157TESTSANDFWSETTINGS_H_ */
