#############################################################
#
# Copyright 2015 F4E | European Joint Undertaking for ITER 
#  and the Development of Fusion Energy ('Fusion for Energy')
# 
# Licensed under the EUPL, Version 1.1 or - as soon they 
# will be approved by the European Commission - subsequent  
# versions of the EUPL (the "Licence"); 
# You may not use this work except in compliance with the 
# Licence. 
# You may obtain a copy of the Licence at: 
#  
# http://ec.europa.eu/idabc/eupl
#
# Unless required by applicable law or agreed to in 
# writing, software distributed under the Licence is 
# distributed on an "AS IS" basis, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
# express or implied. 
# See the Licence for the specific language governing 
# permissions and limitations under the Licence. 
#
# $Id: Makefile.inc 3 2012-01-15 16:26:07Z aneto $
#
#############################################################

TARGET=cov

include Makefile.inc

LIBRARIES_STATIC=EpicsDataSource/cov/EpicsDataSourceTest$(LIBEXT)
LIBRARIES_STATIC+=FileDataSource/cov/FileDataSourceTest$(LIBEXT)
LIBRARIES_STATIC+=LinuxTimer/cov/LinuxTimerTest$(LIBEXT)
LIBRARIES_STATIC+=LoggerDataSource/cov/LoggerDataSourceTest$(LIBEXT)
LIBRARIES_STATIC+=RealTimeThreadSynchronisation/cov/RealTimeThreadSynchronisationTest$(LIBEXT)

ifdef CODAC_ROOT
LIBRARIES_STATIC+=DAN/cov/DANTest$(LIBEXT)
LIBRARIES_STATIC+=NI6259/cov/NI6259Test$(LIBEXT)
LIBRARIES_STATIC+=NI6368/cov/NI6368Test$(LIBEXT)
endif

ifdef MDSPLUS_DIR
LIBRARIES_STATIC+=MDSWriter/cov/MDSWriterTest$(LIBEXT)
endif

ifdef EPICS_BASE
LIBRARIES_STATIC+=EPICSCA/cov/EPICSCATest$(LIBEXT)
endif

# Inclusion of SDNPublisher DataSource is contingent to availability of SDN core library, etc.
ifneq "$(or $(CODAC_VERSION),$(SDN_CORE_LIBRARY_DIR))" ""
LIBRARIES_STATIC+=SDN/cov/SDNTest$(LIBEXT)
endif
