#############################################################
#
# Copyright 2015 F4E | European Joint Undertaking for ITER 
#  and the Development of Fusion Energy ('Fusion for Energy')
# 
# Licensed under the EUPL, Version 1.1 or - as soon they 
# will be approved by the European Commission - subsequent  
# versions of the EUPL (the "Licence"); 
# You may not use this work except in compliance with the 
# Licence. 
# You may obtain a copy of the Licence at: 
#  
# http://ec.europa.eu/idabc/eupl
#
# Unless required by applicable law or agreed to in 
# writing, software distributed under the Licence is 
# distributed on an "AS IS" basis, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
# express or implied. 
# See the Licence for the specific language governing 
# permissions and limitations under the Licence. 
#
#############################################################

TARGET=cov

include Makefile.inc
INCLUDES += -I$(MARTe2_DIR)/Lib/gtest-1.7.0/include

LIBRARIES   += ../../Source/Components/DataSources/$(TARGET)/DataSources$(LIBEXT)
LIBRARIES   += ../../Source/Components/GAMs/$(TARGET)/GAMs$(LIBEXT)
LIBRARIES   += ../../Source/Components/Interfaces/$(TARGET)/Interfaces$(LIBEXT)
LIBRARIES   += ../../Test/Components/Interfaces/$(TARGET)/InterfacesTests$(LIBEXT)
LIBRARIES   += ../../Test/Components/DataSources/$(TARGET)/DataSourcesTests$(LIBEXT)
LIBRARIES   += ../../Test/Components/GAMs/$(TARGET)/GAMsTests$(LIBEXT)

LIBRARIES   += -L$(MARTe2_DIR)/Build/x86-linux/Core/ -lMARTe2
LIBRARIES   += $(MARTe2_DIR)/Lib/gtest-1.7.0/libgtest.a 

ifdef CODAC_ROOT
LIBRARIES += -L$(CODAC_ROOT)/lib/
LIBRARIES += -lnisync
LIBRARIES += -lnixseries
LIBRARIES += -lpxi6259
LIBRARIES += -lNiFpga

## Only force EPICSPVA if CCS version is gt v6.1
CCSGT61 = $(shell if [ `codac-version -v | sed 's/\(.*\)\.\(.*\)/\1\2/g'` -ge 61 ]; then echo 1; else echo 0; fi)
ifeq "$(CCSGT61)" "1"
EPICSPVA = "1"
endif

endif

ifdef EFDA_MARTe_DIR
LIBRARIES   += -L$(EFDA_MARTe_DIR)/Interfaces/BaseLib2Adapter/linux -lBaseLib2Adapter -L$(EFDA_MARTe_DIR)/BaseLib2/linux -lBaseLib2
endif

ifdef MDSPLUS_DIR
LIBRARIES += -L$(MDSPLUS_DIR)/lib -lMdsObjectsCppShr
endif

ifdef EPICS_BASE
LIBRARIES += -L$(EPICS_BASE)/lib/$(EPICS_HOST_ARCH)/ -lca
endif

ifdef EPICSPVA
LIBRARIES += -lpvaClient -lpvAccess -lpvData -lpvDatabase
endif 

ifdef MATLAB_DIR
LIBRARIES += -Wl,-rpath-link,$(MATLAB_DIR)/bin/glnxa64 "$(MATLAB_DIR)/sys/os/glnxa64/libstdc++.so.6" -L$(MATLAB_DIR)/extern/bin/glnxa64/ -L$(MATLAB_DIR)/bin/glnxa64/ -lMatlabDataArray -lMatlabEngine -lmx -lmex -lmat -lm -lstdc++ -leng
endif

ifdef OPEN62541_LIB
LIBRARIES += $(OPEN62541_LIB)/libopen62541$(LIBEXT)
endif


