#############################################################
#
# Copyright 2015 F4E | European Joint Undertaking for ITER 
#  and the Development of Fusion Energy ('Fusion for Energy')
# 
# Licensed under the EUPL, Version 1.1 or - as soon they 
# will be approved by the European Commission - subsequent  
# versions of the EUPL (the "Licence"); 
# You may not use this work except in compliance with the 
# Licence. 
# You may obtain a copy of the Licence at: 
#  
# http://ec.europa.eu/idabc/eupl
#
# Unless required by applicable law or agreed to in 
# writing, software distributed under the Licence is 
# distributed on an "AS IS" basis, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
# express or implied. 
# See the Licence for the specific language governing 
# permissions and limitations under the Licence. 
#
#############################################################


include Makefile.inc
INCLUDES += -I$(MARTe2_DIR)/Lib/gtest-1.7.0/include

LIBRARIES   += ../../Build/$(TARGET)/Components/DataSources/DataSources$(LIBEXT)
LIBRARIES   += ../../Build/$(TARGET)/Components/DataSources/DataSourcesTests$(LIBEXT)
LIBRARIES   += ../../Build/$(TARGET)/Components/GAMs/GAMs$(LIBEXT)
LIBRARIES   += ../../Build/$(TARGET)/Components/GAMs/GAMsTests$(LIBEXT)
LIBRARIES   += ../../Build/$(TARGET)/Components/Interfaces/Interfaces$(LIBEXT)
LIBRARIES   += ../../Build/$(TARGET)/Components/Interfaces/InterfacesTests$(LIBEXT)

LIBRARIES   += -L$(MARTe2_DIR)/Build/$(TARGET)/Core/ -lMARTe2
LIBRARIES   += $(MARTe2_DIR)/Lib/gtest-1.7.0/libgtest.a $(MARTe2_DIR)/Lib/gtest-1.7.0/libgtest_main.a

ifdef CODAC_ROOT
LIBRARIES += -L$(CODAC_ROOT)/lib/ -lnixseries
LIBRARIES += -L$(CODAC_ROOT)/lib/ -lpxi6259
endif

ifdef EFDA_MARTe_DIR
LIBRARIES   += -L$(EFDA_MARTe_DIR)/Interfaces/BaseLib2Adapter/linux -lBaseLib2Adapter -L$(EFDA_MARTe_DIR)/BaseLib2/linux -lBaseLib2
endif

ifdef MDSPLUS_DIR
LIBRARIES += -L$(MDSPLUS_DIR)/lib64 -lMdsObjectsCppShr
endif

ifdef EPICS_BASE
LIBRARIES += -L$(EPICS_BASE)/lib/$(EPICS_HOST_ARCH)/ -lca
endif