#############################################################
#
# Copyright 2015 F4E | European Joint Undertaking for ITER 
#  and the Development of Fusion Energy ('Fusion for Energy')
# 
# Licensed under the EUPL, Version 1.1 or - as soon they 
# will be approved by the European Commission - subsequent  
# versions of the EUPL (the "Licence"); 
# You may not use this work except in compliance with the 
# Licence. 
# You may obtain a copy of the Licence at: 
#  
# http://ec.europa.eu/idabc/eupl
#
# Unless required by applicable law or agreed to in 
# writing, software distributed under the Licence is 
# distributed on an "AS IS" basis, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
# express or implied. 
# See the Licence for the specific language governing 
# permissions and limitations under the Licence. 
#
# $Id: Makefile.inc 3 2012-01-15 16:26:07Z aneto $
#
#############################################################

TARGET=cov

include Makefile.inc

LIBRARIES_STATIC=MemoryGate/cov/MemoryGateTest$(LIBEXT)
LIBRARIES_STATIC+=SysLogger/cov/SysLoggerTest$(LIBEXT)

ifdef CODAC_ROOT
LIBRARIES_STATIC+=NI9157Device/cov/NI9157DeviceTest$(LIBEXT)
LIBRARIES_STATIC+=TcnTimeProvider/cov/TcnTimeProviderTest$(LIBEXT)
endif

ifdef EFDA_MARTe_DIR
LIBRARIES_STATIC+=BaseLib2Wrapper/cov/BaseLib2WrapperTest$(LIBEXT)
endif

ifdef EPICS_BASE
LIBRARIES_STATIC+=EPICS/cov/EPICSTest$(LIBEXT)
endif


ifdef MDSPLUS_DIR
LIBRARIES_STATIC+=MDSStructuredDataI/cov/MDSStructuredDataITest$(LIBEXT)
endif

ifdef EPICSPVA
LIBRARIES_STATIC+=EPICSPVA/cov/EPICSPVATest$(LIBEXT)
endif

ifdef OPEN62541_LIB
LIBRARIES_STATIC+=OPCUA/cov/OPCUATest$(LIBEXT)
endif
